Home work 11
PavelSemenovNickolaevich/MyRecipesBook pull request #11
Opened 2022-12-08 06:31 UTC by PavelSemenovNickolaevich

Создать класс-наследник от ViewModel
Создать метод, который обращается к Retrofit и получает список рецептов
Отправлять список рецептов через LiveData во фрагмент
Обновлять UI во фрагменте чтобы отобразить список в RecyclerView
Опционально. Отправлять ошибку через LiveData  (на вызов onFailure во viewModel в методе получения данных) во фрагмент и показывать текст: Произошла ошибка.

Возможно как-то плохо я освоил тему, кратко объясню что делаю:
1)d FavoriteViewModel вызываю апишку и делаю новый метод который возвращает респонс или ошибку. Так же две переменных на лайфдата: в onResponse r favoriteLiveData.value мапю ответ из body. В onFailure ошибку
2)В. FavoriteFragment  favoriteLiveData.observe устанавливаю адаптер , в errorLiveData.observe выводится ошибка. Ну и вызываю сам метод , который возвращает список

И сразу несколько вопросов.
1)Правильно ли, методы get которые возвращают информацию при переходе на вкладку должны находиться в а в onCreateView?
2)Вы написали , что в горизолнтально recycle view надо тоже использовать dishentity, но тогда не очень понимаю из какого recycle записать данные в базу, из вертикального, то что метод из сети возвращает?
3)Вот по этой части"Тут тогда обращение нужно к полю из build.gralde, это делается через сгенерированный BuildConfig.BASE_URL" Не видит конфиг никак , смотрел  в интернете. Но не находит конфиг

2022-12-10 10:18 UTC, AndroidStudentClub commented
3) Надо попробовать сбилдить проект - билд конфиг после сборки приложения поялвяется - так что это нормально если он красным будет подсвечиваться. Или даже проект не собирается?
2) Данные в базу надо записывать по нажатию на чекбокс - из вертикального
1) Методы желательно вызывать из блока init во viewModel Потому что onCreateView часто вызывается при пересоздании - вот чтобы не делать запросы часто - то делается это в init блоке

2022-12-10 10:31 UTC, AndroidStudentClub requested changes
C созданием репозитория и вынесением логики вижу что получилось разобраться, а вот про работу ViewModel написал комментарии. Самое главное - ViewModel не должна содеражть никаких View. Она общается с фрагментами через LiveData

2022-12-10 10:31 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/viewmodel/FavoriteViewModel.kt
> +    fun getRecipeFromNetwork(recycleViewDish: RecyclerView) {
Не, точно не так

2022-12-10 10:31 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/viewmodel/FavoriteViewModel.kt
> +    fun getRecipeFromNetwork(recycleViewDish: RecyclerView) {
Во ViewModel ни в коем случае нельзя передавать View, это противоречит  MVVM и может вести к утечкам памяти. View (фрагмент или активити и ее виджеты) должны быть просто пассивным наблюдателем за изменениями которые предеает ей ViewModel через LiveData

2022-12-10 10:31 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/viewmodel/FavoriteViewModel.kt
> +    fun getRecipeFromNetwork(recycleViewDish: RecyclerView) {
Поэтому порядок тут должен быть такой
1) В блоке init{} у ViewModel вызвать метод получения рецпетов
2) Через LiveData передать результат
3) В Фрагменте подписаться на LiveData
4) В Методе observe от LiveData уже закидывать данные в RecycerView
Тут аргумента  в виде RecyclerView не должно быть

2022-12-10 10:31 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/viewmodel/FavoriteViewModel.kt
> +                recycleViewDish.adapter = favoriteLiveData.value?.let {
Вот это должно быть в fragment

2022-12-10 10:31 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/fragment/FavoriteFragment.kt
> +        favoriteViewModel.getRecipeFromNetwork(recycleViewDish)
Этот вызов должен быть в init{} в ViewModel

2022-12-10 10:31 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/fragment/FavoriteFragment.kt
> +            DishAdapterVertical(it, R.layout.list_item_vertical_dish)
Вот тут нужно отображать данные в RecyclerView

2022-12-12 19:56 UTC, AndroidStudentClub requested changes
Добавил еще идей для улучшения

2022-12-12 19:56 UTC, AndroidStudentClub commented on app/build.gradle
> +            buildConfigField "String", 'BASE_URL', "https://61e46d241a976f00176ee4a1.mockapi.io/api/v1/"
Нужно добавить debug
И прописать
```
    debug {
            buildConfigField "String", 'BASE_URL', "\"https://61e46d241a976f00176ee4a1.mockapi.io/api/v1/\""
        }
```

2022-12-12 19:56 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/viewmodel/FavoriteViewModel.kt
> +        getRecipeFromNetwork()
Ага, так. Теперь если попереварачивать экран - можно увидеть что запрос вызывается только 1 раз

2022-12-12 19:56 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/viewmodel/FavoriteViewModel.kt
> +        getRecipeFromNetwork()
Тем самым не делаем лишних запросов - приложение работает быстрее и не есть трафик/батарейку

2022-12-12 19:56 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/viewmodel/FavoriteViewModel.kt
>      val favoriteLiveData = MutableLiveData<RecipesResponse>()
Можно еще как улучшение сделать это private поля а публичные будут только LiveData.
Не рекомендуется использовать публичные  MutableLiveData

2022-12-12 20:03 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/viewmodel/FavoriteViewModel.kt
>      val favoriteLiveData = MutableLiveData<RecipesResponse>()
Пример
```
   private val _dataLoading = MutableLiveData<Boolean>()
    val dataLoading: LiveData<Boolean> = _dataLoading
```

2022-12-12 20:51 UTC, PavelSemenovNickolaevich commented on app/build.gradle
> +            buildConfigField "String", 'BASE_URL', "https://61e46d241a976f00176ee4a1.mockapi.io/api/v1/"
пофиксил

2023-01-04 10:19 UTC, merged