Db coroutines
PavelSemenovNickolaevich/MyRecipesBook pull request #13
Opened 2022-12-22 19:05 UTC by PavelSemenovNickolaevich

2022-12-24 19:39 UTC, AndroidStudentClub requested changes
Проверил

2022-12-24 19:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/adapter/DishAdapterHorizontal.kt
> +                searhViewModelVertical.saveFavoriteDish(recipeDish)
Нет, не совсем так. ViewModel не нужно передавать в adapter. Задача адаптера просто отображать данные и говорить что на какой-то элемент адаптеры было нажатие.
Есть же уже метод listener.onClickFavoriteDishCheckBox - вот в него например можно передать модель которую пользователь лайкнул, а потом во фрагменте нужно уже вызвать             searhViewModelVertical.saveFavoriteDish(recipeDish)

2022-12-24 19:39 UTC, AndroidStudentClub commented on app/build.gradle
> +//    androidTestImplementation"androidx.room:room-testing:$rootProject.roomVersion"
Для исопльзованися рума и корутин не хватало нужных зависимостей - поэтому была ошибка
вот так нужно:
```
    def room_version = "2.4.3"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
```

2022-12-24 19:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/fragment/SearchFragment.kt
> +        searhViewModelVertical = ViewModelProvider(this)[SearchViewModel::class.java]
Если у ViewModel есть аргументы в конструкторе  -то нужно обязатаельно использовать Factory
Вот так:
```
  val viewModelFactory = SearchViewModelFactory(
            requireActivity().application
        )
        searhViewModelVertical =   ViewModelProvider(this, viewModelFactory).get(SearchViewModel::class.java)
       
```

2022-12-24 19:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/fragment/SearchFragment.kt
> +        searhViewModelVertical = ViewModelProvider(this)[SearchViewModel::class.java]
Сама Factory вот так будет выглядеть:
```
    class SearchViewModelFactory(
        private val application: Application
    ) : ViewModelProvider.Factory {

        override fun <T : ViewModel> create(modelClass: Class<T>): T {
            return SearchViewModel(application) as T
        }
    }
```

2022-12-24 19:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/fragment/SearchFragment.kt
> +        searhViewModelVertical = ViewModelProvider(this)[SearchViewModel::class.java]
Кроме этого увидел у ViewModel в аргументе context. Вообще по-хорошему туда уже передавать саму базу а не context. Но если хочется context - то контекстов есть два Application контекст и активити. Вот активити категорически нельзя передавать во viewmodel потому что могут быть утечки памяти. Поэтому в Factory указал аргумент Application

2022-12-24 19:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/ui/fragment/SearchFragment.kt
> +        val dishFromDb = context?.let { DishRepository(it) }?.getFavoriteDishByLike()
Вся работа с БД должна быть в view model.
Фрагмент должен только передавать события от ClickListener или получать оповещения о том, чтобы отобразить какие то данные. Ну либо методы к viewmodel. dishFromDb - это дата слой. Работать с ним тут не хорошо.

2022-12-28 21:16 UTC, PavelSemenovNickolaevich commented on app/src/main/java/ru/android/myrecipesbook/adapter/DishAdapterHorizontal.kt
> +                searhViewModelVertical.saveFavoriteDish(recipeDish)
Наконец-то разобрался! спасибо, заработало!

2023-01-04 10:13 UTC, PavelSemenovNickolaevich commented on app/src/main/java/ru/android/myrecipesbook/ui/fragment/SearchFragment.kt
> +        searhViewModelVertical = ViewModelProvider(this)[SearchViewModel::class.java]
Поправил

2023-01-04 10:14 UTC, PavelSemenovNickolaevich commented on app/src/main/java/ru/android/myrecipesbook/ui/fragment/SearchFragment.kt
> +        val dishFromDb = context?.let { DishRepository(it) }?.getFavoriteDishByLike()
поправил

2023-01-04 10:19 UTC, merged