added WelcomeActivity, RegistrationActivity, MainActivity,  ReceipeDe…
PavelSemenovNickolaevich/MyRecipesBook pull request #3
Opened 2022-10-30 19:50 UTC by PavelSemenovNickolaevich

Добавил новые активити, верстка, минимальная логика на валидацию полей.

2022-11-01 20:40 UTC, AndroidStudentClub requested changes
Проверил

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/values/strings.xml
> +    <string name="ingredients_title_header">Ингредиенты</string>
По ингридиентам для Enum - можно еще вот так сделать:
enum class Ingridient(@StringRes val ingridientName: Int) {
    SUGAR(R.string.sugar_name)
}

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/values/strings.xml
> +    <string name="ingredients_title_header">Ингредиенты</string>
Таким образом у нас есть и тип и если нужно - то можно получить название. При этом название не хардкодится - а используется ресурс из строк, и мы получим перевод если приложение с несколькими языками

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/text_input_password"
Для прозрачного фона можно установить такой атрибут в TextInputEditText
android:background="@android:color/transparent"

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/text_input_email"
Для прозрачного фона можно установить такой атрибут в TextInputEditText
android:background="https://github.com/android:color/transparent"

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/text_input_name"
Для прозрачного фона можно установить такой атрибут в TextInputEditText
android:background="https://github.com/android:color/transparent"

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +        android:layout_below="@+id/text_input_email_layout"
А тут для красоты и чтобы хинт не сливался можно еще вот такие атрибуты добавить:
```
        app:startIconTint="#FFFFFF"
        app:boxStrokeColor="@color/white"
        app:placeholderTextColor="@color/white"
        android:textColorHint="@color/white"
        app:hintTextColor="@color/white"
```

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/registrationBtn"
Тут достаточно Button и задать ему фон в виде оранжевого цвета

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/registrationBtn"
Пример:
```
       <Button
            android:id="@+id/registrationBtn"
            android:layout_width="315dp"
            android:text="Регистрация"
            android:textColor="@color/white"
            android:layout_height="55dp"
            app:backgroundTint="#F55A00"
            />
```

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:layout_width="wrap_content"
Можно удалить, так как у Button есть свойство text

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:layout_width="315dp"
Задавать точные размеры плохая практика - нужно стараться делать дизайн адаптивным. Например если будет планшет - то кнопка будет казаться маленькой. Можно попробовать задать ей просто отступы слева/справа - тогда она будет тянуться по ширине экрана. Но это как пример.

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:layout_width="315dp"
Например отступы по 30dp слева/справа

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +            android:layout_width="315dp"
Либо добавить падинги внутри кнопки и расположить ее по центру через layout gravity
```
        <Button
            android:id="@+id/registrationBtn"
            android:layout_width="wrap_content"
            android:layout_height="55dp"
            android:layout_gravity="center"
            android:paddingLeft="46dp"
            android:paddingRight="46dp"
            android:text="Регистрация"
            android:textColor="@color/white"
            app:backgroundTint="#F55A00" />
```

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_registration.xml
> +    <TextView
Да, такой текст можно сделать и так - но это не самый лучший способ, потому что нужно работать с 2 мя виджетами, ставить для них отступы итд. Тут можно использовать Spannable
https://stackoverflow.com/a/7208517
https://developer.android.com/reference/android/text/Spannable.html
Это такая штука которая позволяет использовать один TextView и менять только часть текста

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +                if (userName.text!!.length < MIN_NAME_SYMBOLS)
Использование оператора !! плохая практика, в котлине можно сделать проверку через let
```
        userName.text?.let {
                    if (it.length < MIN_NAME_SYMBOLS)
                        userName.error = resources.getString(R.string.wrong_name)
                }
```

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +                if (userName.text!!.length < MIN_NAME_SYMBOLS)
То есть этот код значит:
```
if (userName.text!=null){
                    if (userName.text.length < MIN_NAME_SYMBOLS)
                        userName.error = resources.getString(R.string.wrong_name)
                }
}
```

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +                if (userName.text!!.length < MIN_NAME_SYMBOLS)
It - это значение которое мы получаем после проверки

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +                if (email.text!!.length < MIN_EMAIL_SYMBOLS || !email.text!!.contains("@"))
Нужно стараться избегать оператора !! как я показал выше например, иначе можно получить NPE рано или поздно

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +                if (password.text!!.length < MIN_PASSWORD_SYMBOLS)
Нужно стараться избегать оператора !! как я показал выше например, иначе можно получить NPE рано или поздно

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +        if (v != null) {
Можно через let

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/java/ru/android/myrecipesbook/WelcomeActivity.kt
> +        if (v != null) {
Можно через let

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_login.xml
> +            android:layout_width="315dp"
тут тоже как и в activity_registration

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_login.xml
> +        android:layout_marginStart="260dp"
Лучше размеры/отсутпы тоже выносить в ресурсы (в dimens.xml) для дальнешейго переиспользования

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_login.xml
> +        app:startIconDrawable="@drawable/password">
Иконки лучше добавлять как векторные в формате xml - они так меньше места занимают и более адаптивны для большого разрешения.  Можно их из svq импортировать/либо даже из андроид студио такие же добавить в проект из набора дефолтных

2022-11-01 20:40 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_login.xml
> +        app:startIconDrawable="@drawable/password">
https://www.geeksforgeeks.org/how-to-add-vector-assets-in-android-studio/

2022-11-04 08:26 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_login.xml
> +        app:startIconDrawable="@drawable/password">
Поправил

2022-11-04 08:27 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/text_input_password"
чуть сделал по другому , добавил style="@style/Widget.Design.TextInputLayout" , все работает корректно

2022-11-04 08:27 UTC, PavelSemenovNickolaevich commented on app/src/main/res/values/strings.xml
> +    <string name="ingredients_title_header">Ингредиенты</string>
Поправил

2022-11-04 08:28 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/text_input_email"
Поправил , добавил стиль style="@style/Widget.Design.TextInputLayout"

2022-11-04 08:28 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/text_input_name"
Поправил , добавил стиль style="@style/Widget.Design.TextInputLayout"

2022-11-04 08:30 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_registration.xml
> +        android:layout_below="@+id/text_input_email_layout"
Готово

2022-11-04 08:31 UTC, PavelSemenovNickolaevich commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +        if (v != null) {
Поправил

2022-11-04 08:31 UTC, PavelNickolaevich commented on app/src/main/java/ru/android/myrecipesbook/WelcomeActivity.kt
> +        if (v != null) {
Поправил

2022-11-04 08:31 UTC, PavelSemenovNickolaevich commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +                if (userName.text!!.length < MIN_NAME_SYMBOLS)
Поправил

2022-11-04 08:31 UTC, PavelSemenovNickolaevich commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +                if (password.text!!.length < MIN_PASSWORD_SYMBOLS)
Поправил

2022-11-04 12:27 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_login.xml
> +        android:layout_marginStart="260dp"
Поправил

2022-11-04 12:28 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/registrationBtn"
Поправил

2022-11-04 12:28 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/registrationBtn"
Сделал все по науке  через shape в  xml ,добавил нужный цвет и подтягиваю через background. Но нужный цвет не подтягивается.

2022-11-04 12:29 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_registration.xml
> +            android:layout_width="315dp"
Поправил

2022-11-04 12:29 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_registration.xml
> +            android:layout_width="wrap_content"
Поправил

2022-11-04 12:29 UTC, PavelSemenovNickolaevich commented on app/src/main/java/ru/android/myrecipesbook/RegistrationActivity.kt
> +                if (email.text!!.length < MIN_EMAIL_SYMBOLS || !email.text!!.contains("@"))
Поправил

2022-11-04 12:35 UTC, merged