added binding, activity_filter, activity_receipe_details.xml
PavelSemenovNickolaevich/MyRecipesBook pull request #5
Opened 2022-11-08 19:49 UTC by PavelSemenovNickolaevich

добавил  биндинги, активити с фильтрацией и активити рецепта

2022-11-09 22:00 UTC, AndroidStudentClub requested changes
Проверил

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +            android:text="Фильтр"
Захардкоженный текст - лучше выносить строки в ресурсы

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +            android:text="Очистить"
Захардкоженный текст - лучше выносить строки в ресурсы

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +        android:text="Прием пищи"
Захардкоженный текст - лучше выносить строки в ресурсы

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +            android:text="Ужин"
Не, тут ошибка. Ужин тоже должен быть в той же группе что и завтра/обед. Там же можно выбрать только один вариант - а если у нас две группы - то получается можно выбрать и завтрак и ужин, что не правильно.
Возможно так было сделано чтобы поместить Ужин ниже строки с завтраком/обедом - но для этого достаточно просто убрать аттрибут    app:singleLine="true" у группы android:id="@+id/meals_cg"

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +            android:text="Ужин"
Итого 1) Переместить Chip с ужином в группу  android:id="@+id/meals_cg" 2) Убрать app:singleLine="true" у группы meals_cg а это удалить

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +        app:chipSpacingHorizontal="@android:dimen/app_icon_size"
Какой-то странный отступ app:chipSpacingHorizontal="android:dimen/app_icon_size"
Тут можно просто 8 dp например ну или 16

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +        app:chipBackgroundColor="@color/orange"
Чтобы цвет при нажатии менялся - то можно задать это через стиль+селектор
https://stackoverflow.com/a/52291297

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +            android:text="Мясные блюда"
Здесь тоже должно быть все в одной группе

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +        android:id="@+id/rating_seekbar"
Тут бы для каждого ползунка еще писать значение которое выбрал пользователь - можно это писать справа - напротив Заголовка ползунка, то есть что-то типа 
Рейтинг             5

2022-11-09 22:00 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_receipe_details.xml
> +        android:layout_marginStart="80dp"
можно marginHorizontal

2022-11-10 16:37 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_filter.xml
> +            android:text="Фильтр"
Да, согласен, но я решил оставить на потом, вдруг что-то переделывать надо будет или удалять и будут особенности реализации какие-либо

2022-11-10 16:38 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_filter.xml
> +        android:text="Прием пищи"
Да, согласен, но я решил оставить на потом, вдруг что-то переделывать надо будет или удалять и будут особенности реализации какие-либо

2022-11-10 16:38 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_filter.xml
> +            android:text="Очистить"
Да, согласен, но я решил оставить на потом, вдруг что-то переделывать надо будет или удалять и будут особенности реализации какие-либо

2022-11-10 19:22 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_filter.xml
> +            android:text="Ужин"
Поправил, сделал в одном чипе, в несколько строк

2022-11-10 19:23 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_filter.xml
> +        app:chipSpacingHorizontal="@android:dimen/app_icon_size"
убрал

2022-11-10 19:40 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_filter.xml
> +        app:chipBackgroundColor="@color/orange"
Добавил

2022-11-10 19:40 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_filter.xml
> +            android:text="Мясные блюда"
Исправил

2022-11-10 19:41 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_filter.xml
> +        android:id="@+id/rating_seekbar"
Добавил как в макете

2022-11-10 19:47 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_receipe_details.xml
> +        android:layout_marginStart="80dp"
поправил

2022-11-10 19:50 UTC, PavelSemenovNickolaevich commented
Поправил замечания

2022-11-10 19:51 UTC, merged