added SearchFragment, FavoriteFragment, ProfileFragment, BottomSheetD…
PavelSemenovNickolaevich/MyRecipesBook pull request #6
Opened 2022-11-14 04:34 UTC by PavelSemenovNickolaevich

📌 Создать 3 фрагмента: SearchFragment, FavoriteFragment, ProfileFragment.

📌 Перенести верстку из MainActivity в SearchFragment. 

📌 Создать BottomNavigationBar внутри MainActivity и переключать фрагменты по нажатию кнопок меню. 

Первая кнопка: переключение на SearchFragment
Вторая на FavoriteFragment(пока пустой – там будет список рецептов)
Последняя на ProfileFragment(пока пустой)
📌 Создать BottomSheetDialogFragment и перенести туда верстку с фильтрами

📌 Создать собственный стиль и применить его через тему к BottomSheetDialogFragment, чтобы были скругленные края.

📌  *По нажатию на карточку рецепта (уже на SearchFragment) передавать id рецепта и открывать DetailsActivity. На странице деталей рецепта отображать уже все данные, найденные из FakeRepository по указанному id.

Экраны с регистрацией, логином, деталями рецепта остаются Activity. Создать нужно 4 (3+1 BottomSheetDialogFragment) фрагмента.

2022-11-14 20:58 UTC, AndroidStudentClub requested changes
Проверил

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/menu/menu_bottom_navigation.xml
> +        android:icon="@drawable/ic_search_24px"
Лучше иконки добавлять как xml, можно либо из svg и потом в xml, либо прямо в AndroidStudio добавить из набора:
<img width="551" alt="Снимок экрана 2022-11-14 в 23 14 22" src="https://user-images.githubusercontent.com/12550867/201757192-a7a9c819-cd2b-49ea-9a2e-f253aed81aff.png">
<img width="695" alt="Снимок экрана 2022-11-14 в 23 14 46" src="https://user-images.githubusercontent.com/12550867/201757218-475efc09-1c32-42ab-8981-42e5db6d3a3c.png">
<img width="697" alt="Снимок экрана 2022-11-14 в 23 14 41" src="https://user-images.githubusercontent.com/12550867/201757235-9a91723c-66fe-4e91-8ae4-0c624d656ef0.png">

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_main.xml
> +        app:itemIconTint="@color/orange"
Тут все иконки оранжевого цвета, а нужно, чтобы они меняли цвет только при выборе. Это можно сделать через selector. Например. Создать в res/colors/bottom_bar.xml

<?xml version="1.0" encoding="utf-8"?>
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_checked="true" android:color="@color/orange" />
    <item android:color="@android:color/darker_gray"  />
</selector>
```

Указать
   app:itemIconTint="@color/bottom_bar"
   app:itemTextColor="@color/bottom_bar"
```
    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/navigation_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        app:itemBackground="@color/gray"
        app:itemIconTint="@color/bottom_bar"
        app:itemTextColor="@color/bottom_bar"
        app:menu="@menu/menu_bottom_navigation" />

```

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/values/styles.xml
> +    <style name="AppModalStyle"
Тут чтобы стиль получился как в макете надо вот так:
 ```
    <style name="CustomBottomSheetDialog" parent="@style/ThemeOverlay.MaterialComponents.BottomSheetDialog">
        <item name="bottomSheetStyle">@style/CustomBottomSheet</item>
    </style>

    <style name="CustomBottomSheet" parent="Widget.MaterialComponents.BottomSheet">
        <item name="shapeAppearanceOverlay">@style/CustomShapeAppearanceBottomSheetDialog</item>
    </style>

    <style name="CustomShapeAppearanceBottomSheetDialog" parent="CustomBottomSheet">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSizeTopRight">16dp</item>
        <item name="cornerSizeTopLeft">16dp</item>
        <item name="cornerSizeBottomRight">0dp</item>
        <item name="cornerSizeBottomLeft">0dp</item>
    </style>
```

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Лучше корневым сделать ScrollView - иначе может не влезть весь контент

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            android:text="Фильтр"
Строки/размеры/цвета рекомендуется выносить в xml-файлы

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            android:text="Очистить"
Строки/размеры/цвета рекомендуется выносить в xml-файлы

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            android:text="Завтрак"
Строки/размеры/цвета рекомендуется выносить в xml-файлы

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            android:text="Поздний завтрак"
Строки/размеры/цвета рекомендуется выносить в xml-файлы

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            style="@style/Widget.MaterialComponents.Chip.Choice"
Нужно тут прописать id - шники соответствующие, иначе потом будет не ясно какой чип выбрал пользователь и так для каждого

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            style="@style/Widget.MaterialComponents.Chip.Choice"
Нужно тут прописать id - шники соответствующие, иначе потом будет не ясно какой чип выбрал пользователь и так для каждого

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            style="@style/Widget.MaterialComponents.Chip.Choice"
Нужно тут прописать id - шники соответствующие, иначе потом будет не ясно какой чип выбрал пользователь и так для каждого

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/values/styles.xml
> +    <style name="AppModalStyle"
И не забыть потом указать в themes.xml 
` <item name="bottomSheetDialogTheme">@style/CustomBottomSheetDialog</item>`

2022-11-14 20:58 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_receipe_details.xml
> -        android:checked="false"
Лучше для этого экрана тоже сделать родительский ScrollView - так как контента тут много и все может не влезть.
И там где картинки ингридиентов - можно тоже попробовать ScrollView только горизонтальный.
Вообще там в идеале сделать динамическое добавление ImageView в LinearLayout

Как идея, типа такого:
 ```
       recipeFirst.listIndigrients.forEach {
            var image = ImageView(this)
            image.setImageResource(getPicturesForIngredients(it))

            val marginLayoutParams = ViewGroup.MarginLayoutParams(
                MATCH_PARENT,
                WRAP_CONTENT
            )

            marginLayoutParams.setMargins(
                resources.getDimension(R.dimen.miniMarginFromEdge).toInt(), 0, 0, 0
            )

            image.layoutParams = marginLayoutParams

            linearLayoutForIndigrients.addView(image)
        }
```

2022-11-15 17:03 UTC, PavelNickolaevich commented on app/src/main/res/menu/menu_bottom_navigation.xml
> +        android:icon="@drawable/ic_search_24px"
Поправил

2022-11-15 17:09 UTC, PavelNickolaevich commented on app/src/main/res/layout/activity_main.xml
> +        app:itemIconTint="@color/orange"
Спасибо, поправил

2022-11-15 19:12 UTC, PavelSemenovNickolaevich commented on app/src/main/res/values/styles.xml
> +    <style name="AppModalStyle"
Спасибо, поправил

2022-11-15 19:25 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Поправил

2022-11-15 19:46 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            android:text="Фильтр"
Исправил

2022-11-15 19:47 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            android:text="Очистить"
Исправил

2022-11-15 19:47 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            android:text="Завтрак"
Исправил

2022-11-15 19:47 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            android:text="Поздний завтрак"
Исправил

2022-11-15 19:47 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            style="@style/Widget.MaterialComponents.Chip.Choice"
Исправил

2022-11-15 19:47 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            style="@style/Widget.MaterialComponents.Chip.Choice"
Исправил

2022-11-15 19:47 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
> +            style="@style/Widget.MaterialComponents.Chip.Choice"
Исправил

2022-11-16 18:13 UTC, PavelSemenovNickolaevich commented on app/src/main/res/layout/activity_receipe_details.xml
> -        android:checked="false"
Поправил верстку, код решил чуть на потом оставить

2022-11-16 18:15 UTC, merged